name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - staging
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  check-external-types:
    uses: taiki-e/workflows/.github/workflows/check-external-types.yml@main
  deny:
    uses: taiki-e/workflows/.github/workflows/deny.yml@main
  docs:
    uses: taiki-e/workflows/.github/workflows/docs.yml@main
  tidy:
    uses: taiki-e/workflows/.github/workflows/tidy-rust.yml@main

  test:
    env:
      CARGO_CAREFUL_VERSION: 0.3.0
    strategy:
      fail-fast: false
      matrix:
        rust:
          # This is the minimum supported Rust version of this crate.
          # When updating this, the reminder to update the minimum supported
          # Rust version in README.md and .clippy.toml.
          - nightly-2021-10-11
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup toolchain add ${{ matrix.rust }} --no-self-update --component rust-src && rustup default ${{ matrix.rust }}
      - run: rustup target add thumbv6m-none-eabi
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - name: Pre Cache cargo-careful
        run: |
          mkdir -p .github/caching
          echo "${CARGO_CAREFUL_VERSION}" > .github/caching/cargo-careful.lock
          echo "${{ runner.tool_cache }}/cargo-careful/bin" >> "${GITHUB_PATH}"
        if: matrix.rust == 'nightly'
      - name: Cache cargo-careful
        id: cache-cargo-careful
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/cargo-careful/bin
          key: cargo-careful-bin-${{ hashFiles('.github/caching/cargo-careful.lock') }}
        if: matrix.rust == 'nightly'
      - name: Install cargo-careful
        run: cargo install -f cargo-careful --root "${{ runner.tool_cache }}/cargo-careful" --locked --version "${CARGO_CAREFUL_VERSION}"
        if: matrix.rust == 'nightly' && steps.cache-cargo-careful.outputs.cache-hit != 'true'
      - run: cargo test --workspace --all-features --tests --no-run
        if: matrix.rust != 'nightly'
      - run: cargo test --workspace --all-features
        if: matrix.rust == 'nightly'
      - run: cargo careful test --workspace --all-features
        env:
          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -Z randomize-layout
          RUSTFLAGS: ${{ env.RUSTFLAGS }} -Z randomize-layout
        if: matrix.rust == 'nightly'
      - run: cargo build --manifest-path tests/no-std/Cargo.toml --target thumbv6m-none-eabi
      - run: cargo minimal-versions build --workspace --all-features --ignore-private

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup toolchain add nightly --no-self-update --component miri && rustup default nightly
      - run: cargo miri test --workspace --all-features
        env:
          MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zmiri-retag-fields
          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -Z randomize-layout
          RUSTFLAGS: ${{ env.RUSTFLAGS }} -Z randomize-layout

  # ALL THE PREVIOUS JOBS NEEDS TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  ci-success:
    name: ci
    if: github.event_name == 'push' && success()
    # prettier-ignore
    needs: [check-external-types, deny, docs, tidy, test, miri] # tidy:needs
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        run: exit 0
